name: houshou
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch::pytorch=1.8.1
  - torchvision>=0.9
  - cudatoolkit>=10.2
  - pip
  - pycodestyle
  - numpy
  - pandas
  - pytest
  - tqdm
  - scikit-learn
  - pip:
    - black
    - facenet-pytorch
    - sacred
    - namegenerator
    - pyyaml
    - pytorch-lightning
    - torchmetrics
    - test-tube