name: houshou
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch=1.8.1
  - pytorch::torchvision
  - cudatoolkit=11.1
  - pip
  - pycodestyle
  - numpy
  - pandas
  - pip:
    - black
    - facenet-pytorch