trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/debug
model:
  loss_f: CROSSENTROPY
  loss_a: UNIFORM_KLDIVERGENCE
  learning_rate: 0.01
  weight_attributes: true
  classification_training_scenario: true
  n_classes: 8192
  verifier_args:
    batch_size: 512
    debug: false
    seed: 42
    n_splits: 10
data:
  class_path: houshou.data.CelebA
  init_args:
    data_dir: CelebA_MTCNN
    batch_size: 512
    buffer_size: null
    attribute:
      - Male