trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/debug
model:
  class_path: houshou.systems.TwoStageMultitaskTrainer
  init_args:
    loss_f: CROSSENTROPY
    loss_a: UNIFORM_KLDIVERGENCE
    learning_rate: 0.001
    weight_attributes: true
    classification_training_scenario: true
    reverse_attribute_gradient: false
    n_classes: 8192
    lambda_value: -1
    verifier_args:
      batch_size: 512
      debug: false
      seed: 42
      n_splits: 10
data:
  class_path: houshou.data.CelebA
  init_args:
    data_dir: CelebA_MTCNN
    batch_size: 512
    buffer_size: null
    attribute:
      - Male