trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/debug
  fast_dev_run: true
model:
  loss_f: SEMIHARD_MINED_TRIPLETS
  loss_a: UNIFORM_KLDIVERGENCE
  learning_rate: 0.01
  weight_attributes: true
  verifier_args:
    batch_size: 512
    debug: true
    seed: 42
    n_splits: 10
data:
  class_path: houshou.data.CelebA
  init_args:
    data_dir: CelebA_MTCNN
    batch_size: 512
    buffer_size: 5000
    attribute:
      - Male