trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/0.5
model:
  class_path: houshou.systems.MultitaskTrainer
  init_args:
    loss: SEMIHARD_CROSSENTROPY
    lambda_value: -1
    learning_rate: 0.01
    classification_training_scenario: false
    reverse_attribute_gradient: false
    weight_attributes: false
    use_pretrained: false
    use_extra_fc_layers: false
    use_short_attribute_branch: true
    verifier_args:
      batch_size: 256
      debug: false
      seed: 42
      n_splits: 10
data:
  class_path: houshou.data.VGGFace2
  init_args:
    data_dir: ~/datasets/vggface2_MTCNN
    batch_size: 512
    buffer_size: 5000
    attribute:
      - Male