trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/0.5
model:
  class_path: houshou.trainers.MultitaskTrainer
  init_args:
    loss: SEMIHARD_CROSSENTROPY
    lambda_value: 0.5
    learning_rate: 0.01
    verifier:
      class_path: houshou.metrics.CVThresholdingVerifier
      init_args:
        batch_size: 256
        seed: 42
        n_splits: 10
data:
  class_path: houshou.data.CelebA
  init_args:
    data_dir: ~/datasets/CelebA_MTCNN
    batch_size: 512
    buffer_size: 5000
    attribute:
      - Male