trainer:
  default_root_dir: /home/gbrown/results/houshou/semihard_mining/debug
model:
  class_path: houshou.systems.TwoStageMultitaskTrainer
  init_args:
    loss_f: SEMIHARD_MINED_TRIPLETS
    loss_a: UNIFORM_KLDIVERGENCE
    learning_rate: 0.01
    lambda_value: -1
    classification_training_scenario: false
    reverse_attribute_gradient: false
    weight_attributes: false
    use_pretrained: false
    use_extra_fc_layers: false
    verifier_args:
      batch_size: 512
      debug: false
      seed: 42
      n_splits: 10
data:
  class_path: houshou.data.CelebA
  init_args:
    data_dir: CelebA_MTCNN
    batch_size: 512
    buffer_size: 5000
    attribute:
      - Male