seed_everything: 42
trainer:
  logger: true
  callbacks: null
  default_root_dir: /home/gbrown/results/houshou/
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 1
  auto_select_gpus: true
  tpu_cores: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: true
  deterministic: false
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false

model:
  class_path: houshou.systems.TwoStageMultitaskTrainer
  init_args:
    loss_f: SEMIHARD_MINED_TRIPLETS
    loss_a: UNIFORM_KLDIVERGENCE
    lambda_value: -1.0
    learning_rate: 0.01
    weight_attributes: false
    classification_training_scenario: false
    n_classes: null
    use_pretrained: false
    use_resnet18: false
    use_resnet101: false
    use_short_attribute_branch: true
    verifier_args:
      batch_size: 512
      debug: false
      seed: 42
      n_splits: 10

data:
  class_path: houshou.data.TripletsAttributeDataModule
  init_args:
    data_dir: null
    batch_size: 512
    buffer_size: 5000
    attribute:
      - Male